/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ShoppingItem {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'unit' : [] | [string],
  'addedBy' : Principal,
  'purchased' : boolean,
  'quantity' : [] | [number],
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItem' : ActorMethod<
    [string, [] | [number], [] | [string], string],
    ShoppingItem
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearPurchased' : ActorMethod<[], bigint>,
  'deleteItem' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItems' : ActorMethod<[], Array<ShoppingItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAnonymous' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'togglePurchased' : ActorMethod<[bigint], ShoppingItem>,
  'updateItem' : ActorMethod<
    [bigint, string, [] | [number], [] | [string], string],
    ShoppingItem
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];