/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShoppingItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'unit' : IDL.Opt(IDL.Text),
  'purchased' : IDL.Bool,
  'quantity' : IDL.Opt(IDL.Float64),
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text), IDL.Text],
      [ShoppingItem],
      [],
    ),
  'clearPurchased' : IDL.Func([], [IDL.Nat], []),
  'deleteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
  'togglePurchased' : IDL.Func([IDL.Nat], [ShoppingItem], []),
  'updateItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text), IDL.Text],
      [ShoppingItem],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShoppingItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'unit' : IDL.Opt(IDL.Text),
    'purchased' : IDL.Bool,
    'quantity' : IDL.Opt(IDL.Float64),
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addItem' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text), IDL.Text],
        [ShoppingItem],
        [],
      ),
    'clearPurchased' : IDL.Func([], [IDL.Nat], []),
    'deleteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
    'togglePurchased' : IDL.Func([IDL.Nat], [ShoppingItem], []),
    'updateItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text), IDL.Text],
        [ShoppingItem],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };